/* ═══════════════════════════════════════════════════════════
   antd Theme — MiniMax Design System
   Maps DESIGN.md tokens to antd ConfigProvider theme
   ═══════════════════════════════════════════════════════════ */

import type { ThemeConfig } from 'antd';

const minimaxTheme: ThemeConfig = {
  token: {
    colorPrimary: '#0a0a0a',
    colorSuccess: '#1ba673',
    colorWarning: '#ff5530',
    colorError: '#d45656',
    colorInfo: '#1456f0',
    colorTextBase: '#0a0a0a',
    colorBgBase: '#ffffff',
    colorBorder: '#e5e7eb',
    colorBgContainer: '#ffffff',
    colorBgLayout: '#f7f8fa',
    colorText: '#222222',
    colorTextSecondary: '#45515e',
    colorTextTertiary: '#5f5f5f',
    colorTextQuaternary: '#8e8e93',
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    fontFamily: "'DM Sans', Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif",
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeSM: 13,
    fontSizeXL: 20,
    lineHeight: 1.5,
    lineHeightLG: 1.4,
    lineHeightSM: 1.5,
    controlHeight: 40,
    controlHeightLG: 44,
    controlHeightSM: 32,
    controlOutline: 'rgba(10, 10, 10, 0.06)',
    marginXS: 8,
    marginSM: 12,
    margin: 16,
    marginMD: 16,
    marginLG: 20,
    marginXL: 24,
    marginXXL: 32,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 16,
    paddingLG: 20,
    paddingXL: 24,
    screenXS: 480,
    screenSM: 576,
    screenMD: 768,
    screenLG: 1024,
    screenXL: 1280,
    boxShadow: 'rgba(0, 0, 0, 0.04) 0px 1px 2px 0px',
    boxShadowSecondary: 'rgba(0, 0, 0, 0.08) 0px 4px 6px 0px',
  },
  components: {
    Button: {
      borderRadius: 9999,
      borderRadiusLG: 9999,
      borderRadiusSM: 9999,
      controlHeight: 38,
      controlHeightLG: 44,
      controlHeightSM: 32,
      fontSize: 14,
      fontWeight: 600,
      paddingContentHorizontal: 24,
      primaryColor: '#ffffff',
      defaultBorderColor: '#e5e7eb',
      // blue is only used for info actions, not as the primary brand color
      primaryShadow: 'none',
    },
    Card: {
      borderRadiusLG: 16,
      paddingLG: 24,
      colorBorderSecondary: '#e5e7eb',
    },
    Table: {
      borderRadius: 8,
      borderRadiusLG: 8,
      headerBg: '#f7f8fa',
      headerColor: '#5f5f5f',
      headerFontSize: 13,
      headerFontWeight: 600,
      rowHoverBg: '#f7f8fa',
      borderColor: '#eaecf0',
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      fontFamily: "'DM Sans', Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif",
    },
    Input: {
      borderRadius: 8,
      borderRadiusLG: 8,
      borderRadiusSM: 6,
      controlHeight: 40,
      colorBorder: '#e5e7eb',
      hoverBorderColor: '#1d4ed8',
      activeBorderColor: '#1d4ed8',
      activeShadow: '0 0 0 2px rgba(29, 78, 216, 0.1)',
    },
    Select: {
      borderRadius: 8,
      borderRadiusLG: 8,
      borderRadiusSM: 6,
      controlHeight: 40,
      colorBorder: '#e5e7eb',
    },
    Menu: {
      radiusItem: 6,
      colorItemBgHover: '#f7f8fa',
      colorItemText: '#222222',
      colorItemTextSelected: '#0a0a0a',
      fontWeightStrong: 500,
    },
    Tabs: {
      borderRadius: 0,
      cardBg: '#ffffff',
      inkBarColor: '#0a0a0a',
      itemColor: '#5f5f5f',
      itemSelectedColor: '#0a0a0a',
      fontSize: 14,
    },
    Tag: {
      borderRadius: 9999,
      fontSize: 13,
      lineHeight: 1.5,
    },
    Badge: {
      borderRadius: 9999,
    },
    Statistic: {
      titleFontSize: 14,
      contentFontSize: 24,
    },
    Form: {
      labelFontSize: 14,
      labelColor: '#222222',
      labelFontWeight: 500,
    },
    Modal: {
      borderRadiusLG: 16,
      boxShadow: 'rgba(36, 36, 36, 0.08) 0px 12px 16px -4px',
    },
    Spin: {
      dotSizeLG: 40,
      dotSize: 32,
    },
  },
};

export default minimaxTheme;
